server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    database: postgresql
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banking_system}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/master.yaml
    enabled: ${LIQUIBASE_ENABLED:true}
  # Добавляем конфигурацию для статических ресурсов
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./docs/

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    url: /api/api-docs.yaml  # Указываем путь к нашему YAML файлу
    config-url: /api/api-docs/swagger-config
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

# Явно указываем путь к OpenAPI файлу
openapi:
  file-path: ./docs/openapi.yaml

logging:
  level:
    com.example.bankcards: ${LOG_LEVEL_COM_EXAMPLE:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:DEBUG}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_HIBERNATE_BINDER:TRACE}

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY:mySuperSecretKey}

jwt:
  secret: ${JWT_SECRET:my-very-secure-key-256-bits-long-1234567890}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds